spring:
  datasource:
    url: jdbc:h2:file:./h2/testdb
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: none

  flyway:
    location: classpath:db/migration
server:
  port: 8081